### ISSUE TITLE
Deployment to the netlify site

### ISSUE THREAD

**Issue by shijiezhou1** [chingu-voyages/v36-toucans-team-05#24]
Since the `calendar-app` or `calendar` is taken in Netlify already, I will make the temporary one with the below URL. 

[https://calendar-v1.netlify.app/](https://calendar-v1.netlify.app/)

Please comment on any name you guys would like to use.

**Comment by Ibinola** [comment]
this is fine.

**Comment by bisioluimoleayo** [comment]
Yes let's make use of the URL
