### ISSUE TITLE
⚙️ Set Up a Team Workflow

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v36-toucans-team-05#9]
**__Task Description__**
- [x] Decide on the coding standards the team must follow.
- [x] Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- [x] Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- [x] Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- [x] Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to [Develop the App](https://docs.google.com/document/d/10erbB9vJbPfRXOad5hPkUv27iqlVGnj1etRu-9QtTjs/edit#heading=h.csvhpxknom3k) to learn more about the types of meetings you’ll need.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Setup Your Team Workflow (Chingu Handbook)](https://docs.chingu.io/voyage/project/workflow)
[Javascript Style Guides](https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa)
[Defining a Git Workflow (Chingu Handbook)](https://docs.chingu.io/techres/gitworkflow)
[Git Branches (Chingu Handbook)](https://docs.chingu.io/techres/gitbranches)
[Git Commits (Chingu Handbook)](https://docs.chingu.io/techres/gitcommits)
[Git Pull Requests (Chingu Handbook)](https://docs.chingu.io/techres/gitprs)

**Comment by shijiezhou1** [comment]
We will follow the same guideline from @jdmedlock 

1. Code Style Guide
A code style guide is a set of standards that outline how the code is written and makes it easier for you to read each other's code. You can follow a style guide per below and/or use a VSCode extension like ESLint or Prettier to format your code every time you save it.

Javascript Style Guides

2. Git Strategy
Just like there are code standards, here are some Git standards and guides to maintain a cohesive workflow with your teammates. Remember there are MANY possible Git workflows that can be used -- we are presenting only one.

Defining a Git Workflow
Git Branches
Git Commits
Git Pull Requests
